version: '3.3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - your_network_name


#  elasticsearch:
##    image: elasticsearch:8.11.0
##    image: launcher.gcr.io/google/elasticsearch2
#    image: elasticsearch:7.8.1
#    environment:
#      - discovery.type=single-node
#    ports:
#      - "9200:9200"
#    networks:
#      - elastic

  django:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/fampay
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - docker_env.env
    networks:
      - your_network_name


  celery:
    container_name: celery-worker
    build:
      context: .
    command: celery -A settings worker -l info -Q fampay-queue-v1
    volumes:
      - .:/fampay
    env_file:
      - docker_env.env
    depends_on:
      - django
      - redis
    networks:
      - your_network_name


  celery-beat:
    container_name: celery-beat-fampay
    build:
      context: .
    command:  celery -A settings beat -l info
    volumes:
      - .:/fampay
    env_file:
      - docker_env.env
    depends_on:
      - redis
      - django
    networks:
      - your_network_name

volumes:
  esdata:

networks:
  your_network_name:
    driver: bridge